version: "3.5"
services:
  elasticsearch:
    container_name: "elasticsearch"
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.3"
    ports:
      - "9200:9200"
    networks:
      - esnet

  app:
    build: .
    ports:
      - "9000:9000"
    container_name: "search-service"
    depends_on:
      - elasticsearch
    networks:
      - esnet
    environment:
      - ELASTIC_URL=http://elasticsearch:9200

networks:
  esnet:
    driver: bridge
